config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get     "/restaurants", to: "restaurants#index"
  post    "/restaurants", to: "restaurants#create"
  get     "/restaurants/new", to: "restaurants#new"
  get     "/restaurants/:id/edit", to: "restaurants#edit"
  get     "/restaurants/:id", to: "restaurants#show", as: :restaurant
  patch   "/restaurants/:id ",to: "restaurants#update"
  delete  "/restaurants/:id", to: "restaurants#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :find_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end
# ​
  def show
    @reviews = @restaurant.reviews
    # @reviews.each do |review|

    # @rating = @reviews.rating
    # @restaurants = Restaurant.find(params[:id])
  end






  private

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
# ​
#   def new
#     @restaurants = Restaurant.new
#   end
# ​
#   def create
#     @restaurants = Restaurant.new(params[:restaurant])
#     @restaurants.save
#   end
# ​
#   def edit
#     @restaurants = Restaurant.find(params[:id])
#   end
# ​
#   def update
#     @restaurants = Restaurant.find(params[:id])
#     @restaurants.update(params[:restaurant])
#   end
# ​
#   def destroy
#     @restaurants = Restaurant.find(params[:id])
#     @restaurants.destroy
#   end


    # private

    # def find_restaurant
    #   @restaurant = Restaurant.find(params[:id])
    # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <script src="https://kit.fontawesome.com/e19203fb96.js" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item active">
          <%= link_to "Home", "#", class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Messages", "#", class: "nav-link" %>
        </li>
        <li class="nav-item dropdown">
          <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Action", "#", class: "dropdown-item" %>
            <%= link_to "Another action", "#", class: "dropdown-item" %>
          </div>
        </li>
      </ul>
    </div>
  </div>
</div>
    <div style="margin: 2% 25%;">
      <%= yield %>
    </div>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>YOUR RESTAURANTS NEAR BY!</h1>
<ul style="list-style:none;">
<div class="cards">
  <% @restaurants.each do |restaurant| %>
  <%= link_to restaurant_path(restaurant) do %>
    <li><div class="card-trip">
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
            <div class="card-trip-infos">
          <div>
            <h2><%= restaurant.name%></h2>
            <p><%= restaurant.address%> | +49<%= restaurant.phone%></p>
         </div>
            <h2 class="card-trip-pricing"><%= restaurant.category%></h2>
            <%# <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" /> %>
        </div>
      </div>
    </li>
    <% end %>
  <% end %>
</div>
</ul>

app/views/restaurants/show.html.erb
<h1>YOUR RESTAURANTS NEAR BY!</h1>
<%# <%= link_to show_restaurant_path(@restaurant) %>
  <%# <% @restaurants.each do |restaurant| %>
        <div class="card-trip">
          <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
          <div class="card-trip-infos">
            <div>
              <h2><%= @restaurant.name%></h2>
              <p><%= @restaurant.address%> | +49<%= @restaurant.phone%></p>
            </div>
              <h2 class="card-trip-pricing"><%= @restaurant.category%></h2>
            <%# <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" /> %>
          </div>
        </div>

  <%# <% end %>
<div class="nebeneinander">
  <% @reviews.each do |review| %>
    <ul>
      <li>
        <div class="card-product">
            <h2><%= review.content %></h2>
              <ul class= "nebeneinander">
                <% review.rating.times do%>
                    <li><i class="fa-solid fa-star"></i></li>
                <% end %>
              </ul>
        </div>
      </li>
    </ul>
  <% end %>
</div>